version: '3'
services:
  dev:
    image: avejidah/node-dubnium:latest
    volumes:
      - .:/home/node/dev
    container_name: formn-dev
    ports:
      - "9229:9229"

  db:
    image: percona:5.7
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    container_name: formn-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=formn-password
      - MYSQL_DATABASE=formn_test_db
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

