import { LexerToken } from './lexer-token';

/**
 * A parse tree that is generated by the [[ConditionParser]].parse method.
 */
export class ParseTree {
  public children: ParseTree[] = [];

  /**
   * Initialize the parse tree.
   */
  constructor(
    public parent: ParseTree,
    public token: LexerToken) {
  }
}

